base_url = "https://docs.worldwidetelescope.org/research-app/latest/"
title = "WWT Research Application Manual"
description = "The WorldWide Telescope research app manual."
theme = "wwtguide"

[markdown]
highlight_code = true

[extra]
github_base = "https://github.com/WorldWideTelescope/wwt-webgl-engine"
google_analytics_id = "G-D1J49XX0CV"
stylesheets = ["extras.css"]

# This is temporary - see https://github.com/WorldWideTelescope/wwt-webgl-engine/issues/345
[link_checker]
skip_prefixes = ["https://www.npmjs.com"]
