base_url = "//docs.worldwidetelescope.org/research-app/1/"
title = "WWT Research Application Manual"
description = "The WorldWide Telescope research app manual."
theme = "wwtguide"

[markdown]
highlight_code = true

[extra]
github_base = "//github.com/WorldWideTelescope/wwt-webgl-engine"
google_analytics_id = "UA-107473046-3"
stylesheets = ["extras.css"]
